import { Router, type IRouter } from "express";
import authRouter from "./auth";
import collectionsRouter from "./collections";
import followsRouter from "./follows";
import tasksRouter from "./tasks";
import streakRouter from "./streak";
import vitrinRouter from "./vitrin";
import healthRouter from "./health";
import productsRouter from "./products";
import categoriesRouter from "./categories";
import scrapeRouter from "./scrape";
import storageRouter from "./storage";
import seoRouter from "./seo";
import imageProxyRouter from "./image-proxy";
import votesRouter from "./votes";
import reviewsRouter from "./reviews";
import alarmsRouter from "./alarms";
import gameRouter from "./game";
import businessRouter from "./business";
import pointsRouter from "./points";
import earningsRouter from "./earnings";
import subscriptionsRouter from "./subscriptions";
import adsRouter from "./ads";
import rankingsRouter from "./rankings";
import adminRouter from "./admin";
import notificationsRouter from "./notifications";
import discoverRouter from "./discover";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/products", productsRouter);
router.use("/products", votesRouter);
router.use("/products", reviewsRouter);
router.use("/products", alarmsRouter);
router.use("/alarms", alarmsRouter);
router.use("/categories", categoriesRouter);
router.use("/scrape", scrapeRouter);
router.use(storageRouter);
router.use(seoRouter);
router.use(imageProxyRouter);
router.use("/game", gameRouter);
router.use("/business", businessRouter);
router.use("/points", pointsRouter);
router.use("/earnings", earningsRouter);
router.use("/subscriptions", subscriptionsRouter);
router.use("/ads", adsRouter);
router.use("/rankings", rankingsRouter);
router.use("/auth", authRouter);
router.use("/collections", collectionsRouter);
router.use("/follows", followsRouter);
router.use("/tasks", tasksRouter);
router.use("/streak", streakRouter);
router.use("/vitrin", vitrinRouter);
router.use("/admin", adminRouter);
router.use("/notifications", notificationsRouter);
router.use("/discover", discoverRouter);

export default router;
